import { fileURLToPath } from "node:url";

const entrypoint = fileURLToPath(new URL("../src/package-manager/entry.ts", import.meta.url));
const destination = fileURLToPath(
  new URL("../src/package-manager-bootstrap.generated.ts", import.meta.url),
);
const result = await Bun.build({
  entrypoints: [entrypoint],
  target: "node",
  format: "cjs",
  minify: { whitespace: true, identifiers: false, syntax: false },
});
if (!result.success)
  throw new AggregateError(result.logs, "Package-manager bootstrap build failed");
const source = (await result.outputs[0].text()).trim();
if (source.includes("\n")) throw new Error("Bootstrap must fit on one Dockerfile RUN line");
const generated = `// Generated by scripts/generate-package-manager-bootstrap.ts. Do not edit.\n// prettier-ignore\nexport const PACKAGE_MANAGER_BOOTSTRAP_SOURCE = ${JSON.stringify(source)};\n`;
if (process.argv.includes("--check")) {
  const file = Bun.file(destination);
  if (!(await file.exists()) || (await file.text()) !== generated)
    throw new Error(
      "Package-manager bootstrap is stale. Run bun run --cwd packages/core generate:bootstrap with the repository-pinned Bun.",
    );
} else {
  await Bun.write(destination, generated);
}
